import type { Book } from "@/types/bible";

export const ESV_BOOKS: Book[] = [
	{ id: "GEN", translationId: "ESV", name: "Genesis", commonName: "Genesis", order: 1, numberOfChapters: 50, firstChapterNumber: 1, lastChapterNumber: 50 },
	{ id: "EXO", translationId: "ESV", name: "Exodus", commonName: "Exodus", order: 2, numberOfChapters: 40, firstChapterNumber: 1, lastChapterNumber: 40 },
	{ id: "LEV", translationId: "ESV", name: "Leviticus", commonName: "Leviticus", order: 3, numberOfChapters: 27, firstChapterNumber: 1, lastChapterNumber: 27 },
	{ id: "NUM", translationId: "ESV", name: "Numbers", commonName: "Numbers", order: 4, numberOfChapters: 36, firstChapterNumber: 1, lastChapterNumber: 36 },
	{ id: "DEU", translationId: "ESV", name: "Deuteronomy", commonName: "Deuteronomy", order: 5, numberOfChapters: 34, firstChapterNumber: 1, lastChapterNumber: 34 },
	{ id: "JOS", translationId: "ESV", name: "Joshua", commonName: "Joshua", order: 6, numberOfChapters: 24, firstChapterNumber: 1, lastChapterNumber: 24 },
	{ id: "JDG", translationId: "ESV", name: "Judges", commonName: "Judges", order: 7, numberOfChapters: 21, firstChapterNumber: 1, lastChapterNumber: 21 },
	{ id: "RUT", translationId: "ESV", name: "Ruth", commonName: "Ruth", order: 8, numberOfChapters: 4, firstChapterNumber: 1, lastChapterNumber: 4 },
	{ id: "1SA", translationId: "ESV", name: "1 Samuel", commonName: "1 Samuel", order: 9, numberOfChapters: 31, firstChapterNumber: 1, lastChapterNumber: 31 },
	{ id: "2SA", translationId: "ESV", name: "2 Samuel", commonName: "2 Samuel", order: 10, numberOfChapters: 24, firstChapterNumber: 1, lastChapterNumber: 24 },
	{ id: "1KI", translationId: "ESV", name: "1 Kings", commonName: "1 Kings", order: 11, numberOfChapters: 22, firstChapterNumber: 1, lastChapterNumber: 22 },
	{ id: "2KI", translationId: "ESV", name: "2 Kings", commonName: "2 Kings", order: 12, numberOfChapters: 25, firstChapterNumber: 1, lastChapterNumber: 25 },
	{ id: "1CH", translationId: "ESV", name: "1 Chronicles", commonName: "1 Chronicles", order: 13, numberOfChapters: 29, firstChapterNumber: 1, lastChapterNumber: 29 },
	{ id: "2CH", translationId: "ESV", name: "2 Chronicles", commonName: "2 Chronicles", order: 14, numberOfChapters: 36, firstChapterNumber: 1, lastChapterNumber: 36 },
	{ id: "EZR", translationId: "ESV", name: "Ezra", commonName: "Ezra", order: 15, numberOfChapters: 10, firstChapterNumber: 1, lastChapterNumber: 10 },
	{ id: "NEH", translationId: "ESV", name: "Nehemiah", commonName: "Nehemiah", order: 16, numberOfChapters: 13, firstChapterNumber: 1, lastChapterNumber: 13 },
	{ id: "EST", translationId: "ESV", name: "Esther", commonName: "Esther", order: 17, numberOfChapters: 10, firstChapterNumber: 1, lastChapterNumber: 10 },
	{ id: "JOB", translationId: "ESV", name: "Job", commonName: "Job", order: 18, numberOfChapters: 42, firstChapterNumber: 1, lastChapterNumber: 42 },
	{ id: "PSA", translationId: "ESV", name: "Psalms", commonName: "Psalms", order: 19, numberOfChapters: 150, firstChapterNumber: 1, lastChapterNumber: 150 },
	{ id: "PRO", translationId: "ESV", name: "Proverbs", commonName: "Proverbs", order: 20, numberOfChapters: 31, firstChapterNumber: 1, lastChapterNumber: 31 },
	{ id: "ECC", translationId: "ESV", name: "Ecclesiastes", commonName: "Ecclesiastes", order: 21, numberOfChapters: 12, firstChapterNumber: 1, lastChapterNumber: 12 },
	{ id: "SNG", translationId: "ESV", name: "Song of Solomon", commonName: "Song of Solomon", order: 22, numberOfChapters: 8, firstChapterNumber: 1, lastChapterNumber: 8 },
	{ id: "ISA", translationId: "ESV", name: "Isaiah", commonName: "Isaiah", order: 23, numberOfChapters: 66, firstChapterNumber: 1, lastChapterNumber: 66 },
	{ id: "JER", translationId: "ESV", name: "Jeremiah", commonName: "Jeremiah", order: 24, numberOfChapters: 52, firstChapterNumber: 1, lastChapterNumber: 52 },
	{ id: "LAM", translationId: "ESV", name: "Lamentations", commonName: "Lamentations", order: 25, numberOfChapters: 5, firstChapterNumber: 1, lastChapterNumber: 5 },
	{ id: "EZK", translationId: "ESV", name: "Ezekiel", commonName: "Ezekiel", order: 26, numberOfChapters: 48, firstChapterNumber: 1, lastChapterNumber: 48 },
	{ id: "DAN", translationId: "ESV", name: "Daniel", commonName: "Daniel", order: 27, numberOfChapters: 12, firstChapterNumber: 1, lastChapterNumber: 12 },
	{ id: "HOS", translationId: "ESV", name: "Hosea", commonName: "Hosea", order: 28, numberOfChapters: 14, firstChapterNumber: 1, lastChapterNumber: 14 },
	{ id: "JOL", translationId: "ESV", name: "Joel", commonName: "Joel", order: 29, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "AMO", translationId: "ESV", name: "Amos", commonName: "Amos", order: 30, numberOfChapters: 9, firstChapterNumber: 1, lastChapterNumber: 9 },
	{ id: "OBA", translationId: "ESV", name: "Obadiah", commonName: "Obadiah", order: 31, numberOfChapters: 1, firstChapterNumber: 1, lastChapterNumber: 1 },
	{ id: "JON", translationId: "ESV", name: "Jonah", commonName: "Jonah", order: 32, numberOfChapters: 4, firstChapterNumber: 1, lastChapterNumber: 4 },
	{ id: "MIC", translationId: "ESV", name: "Micah", commonName: "Micah", order: 33, numberOfChapters: 7, firstChapterNumber: 1, lastChapterNumber: 7 },
	{ id: "NAM", translationId: "ESV", name: "Nahum", commonName: "Nahum", order: 34, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "HAB", translationId: "ESV", name: "Habakkuk", commonName: "Habakkuk", order: 35, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "ZEP", translationId: "ESV", name: "Zephaniah", commonName: "Zephaniah", order: 36, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "HAG", translationId: "ESV", name: "Haggai", commonName: "Haggai", order: 37, numberOfChapters: 2, firstChapterNumber: 1, lastChapterNumber: 2 },
	{ id: "ZEC", translationId: "ESV", name: "Zechariah", commonName: "Zechariah", order: 38, numberOfChapters: 14, firstChapterNumber: 1, lastChapterNumber: 14 },
	{ id: "MAL", translationId: "ESV", name: "Malachi", commonName: "Malachi", order: 39, numberOfChapters: 4, firstChapterNumber: 1, lastChapterNumber: 4 },
	{ id: "MAT", translationId: "ESV", name: "Matthew", commonName: "Matthew", order: 40, numberOfChapters: 28, firstChapterNumber: 1, lastChapterNumber: 28 },
	{ id: "MRK", translationId: "ESV", name: "Mark", commonName: "Mark", order: 41, numberOfChapters: 16, firstChapterNumber: 1, lastChapterNumber: 16 },
	{ id: "LUK", translationId: "ESV", name: "Luke", commonName: "Luke", order: 42, numberOfChapters: 24, firstChapterNumber: 1, lastChapterNumber: 24 },
	{ id: "JHN", translationId: "ESV", name: "John", commonName: "John", order: 43, numberOfChapters: 21, firstChapterNumber: 1, lastChapterNumber: 21 },
	{ id: "ACT", translationId: "ESV", name: "Acts", commonName: "Acts", order: 44, numberOfChapters: 28, firstChapterNumber: 1, lastChapterNumber: 28 },
	{ id: "ROM", translationId: "ESV", name: "Romans", commonName: "Romans", order: 45, numberOfChapters: 16, firstChapterNumber: 1, lastChapterNumber: 16 },
	{ id: "1CO", translationId: "ESV", name: "1 Corinthians", commonName: "1 Corinthians", order: 46, numberOfChapters: 16, firstChapterNumber: 1, lastChapterNumber: 16 },
	{ id: "2CO", translationId: "ESV", name: "2 Corinthians", commonName: "2 Corinthians", order: 47, numberOfChapters: 13, firstChapterNumber: 1, lastChapterNumber: 13 },
	{ id: "GAL", translationId: "ESV", name: "Galatians", commonName: "Galatians", order: 48, numberOfChapters: 6, firstChapterNumber: 1, lastChapterNumber: 6 },
	{ id: "EPH", translationId: "ESV", name: "Ephesians", commonName: "Ephesians", order: 49, numberOfChapters: 6, firstChapterNumber: 1, lastChapterNumber: 6 },
	{ id: "PHP", translationId: "ESV", name: "Philippians", commonName: "Philippians", order: 50, numberOfChapters: 4, firstChapterNumber: 1, lastChapterNumber: 4 },
	{ id: "COL", translationId: "ESV", name: "Colossians", commonName: "Colossians", order: 51, numberOfChapters: 4, firstChapterNumber: 1, lastChapterNumber: 4 },
	{ id: "1TH", translationId: "ESV", name: "1 Thessalonians", commonName: "1 Thessalonians", order: 52, numberOfChapters: 5, firstChapterNumber: 1, lastChapterNumber: 5 },
	{ id: "2TH", translationId: "ESV", name: "2 Thessalonians", commonName: "2 Thessalonians", order: 53, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "1TI", translationId: "ESV", name: "1 Timothy", commonName: "1 Timothy", order: 54, numberOfChapters: 6, firstChapterNumber: 1, lastChapterNumber: 6 },
	{ id: "2TI", translationId: "ESV", name: "2 Timothy", commonName: "2 Timothy", order: 55, numberOfChapters: 4, firstChapterNumber: 1, lastChapterNumber: 4 },
	{ id: "TIT", translationId: "ESV", name: "Titus", commonName: "Titus", order: 56, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "PHM", translationId: "ESV", name: "Philemon", commonName: "Philemon", order: 57, numberOfChapters: 1, firstChapterNumber: 1, lastChapterNumber: 1 },
	{ id: "HEB", translationId: "ESV", name: "Hebrews", commonName: "Hebrews", order: 58, numberOfChapters: 13, firstChapterNumber: 1, lastChapterNumber: 13 },
	{ id: "JAS", translationId: "ESV", name: "James", commonName: "James", order: 59, numberOfChapters: 5, firstChapterNumber: 1, lastChapterNumber: 5 },
	{ id: "1PE", translationId: "ESV", name: "1 Peter", commonName: "1 Peter", order: 60, numberOfChapters: 5, firstChapterNumber: 1, lastChapterNumber: 5 },
	{ id: "2PE", translationId: "ESV", name: "2 Peter", commonName: "2 Peter", order: 61, numberOfChapters: 3, firstChapterNumber: 1, lastChapterNumber: 3 },
	{ id: "1JN", translationId: "ESV", name: "1 John", commonName: "1 John", order: 62, numberOfChapters: 5, firstChapterNumber: 1, lastChapterNumber: 5 },
	{ id: "2JN", translationId: "ESV", name: "2 John", commonName: "2 John", order: 63, numberOfChapters: 1, firstChapterNumber: 1, lastChapterNumber: 1 },
	{ id: "3JN", translationId: "ESV", name: "3 John", commonName: "3 John", order: 64, numberOfChapters: 1, firstChapterNumber: 1, lastChapterNumber: 1 },
	{ id: "JUD", translationId: "ESV", name: "Jude", commonName: "Jude", order: 65, numberOfChapters: 1, firstChapterNumber: 1, lastChapterNumber: 1 },
	{ id: "REV", translationId: "ESV", name: "Revelation", commonName: "Revelation", order: 66, numberOfChapters: 22, firstChapterNumber: 1, lastChapterNumber: 22 },
];
